name: Flower Chart
on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Flower
        uses: martinheinz/contributions-flower@v1.0
        with:
          github_user_name: kfrural
          output_path: dist/contributions.png
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: output
          folder: dist
